### ISSUE TITLE
Inconsistent value of pressure in GCMC

### ISSUE THREAD

**Issue by camjjr** [MaginnGroup/Cassandra#128]
Hi everyone,

I am facing an issue when running a simulation of a binary gas mixture of CO2/N2 in the GCMC ensemble. 
First, I ran a simulation, using the widow method, to calculate the chemical potential for the two species at 313.15 K and 1 atm. With the chemical potentials, I ran a 
GCMC simulation. I would expect to reach the same conditions used to obtain the chemical potentials (313.15 and 1 atm). However, the pressure is very high as the total energy. Can you check if the inputs are correct? I will attach the input and output files.
I tested the chemical potential using LAMMPS and obtained the expected results. I also tested two different versions of Cassandra and obtained the unexpected results.

  [widom.log](https://github.com/MaginnGroup/Cassandra/files/9181922/widom.log)
[widom_input.txt](https://github.com/MaginnGroup/Cassandra/files/9181923/widom_input.txt)
[gcmc.txt](https://github.com/MaginnGroup/Cassandra/files/9181933/gcmc.txt)
[gcmc_NT.txt](https://github.com/MaginnGroup/Cassandra/files/9181934/gcmc_NT.txt)

**Comment by rwsmith7531** [comment]
@camjjr Your log file for your Widom insertions indicates that you used version 1.2.5, but Widom insertions were first released in version 1.2.6.  If your CO2 has nonzero partial charges but your N2 does not, that would have caused bugged behavior in versions prior to the latest version, 1.3.0, where it was fixed.

**Comment by camjjr** [comment]
Hi @rwsmith7531,

I also tested the 1.3.0 version of cassandra, which gives the same results. The output files are attached. In this case, the simulation crashed because of the high number of molecules. Moreover, the N2 has partial charges.
[gcmc_NT_prp.txt](https://github.com/MaginnGroup/Cassandra/files/9234222/gcmc_NT_prp.txt)
[gcmc_NT.log](https://github.com/MaginnGroup/Cassandra/files/9234223/gcmc_NT.log)

**Comment by rwsmith7531** [comment]
@camjjr Did you also use 1.3.0 for the Widom insertions, or just the GCMC?

I notice a number of oddities with your input files.

- Your real-space charge cutoff is vastly different between your simulations.  I don't think this should cause much of a difference, but I recommend keeping it consistent.
- Your `# Fragment_Files` section has "species2" before "species1".  This is not the way the `library_setup.py` script would construct that section for you, and it is confusing.  Listing them in that order causes Cassandra to get the fragment configurations for species 1 from the "species2" fragment library and get the fragment configurations for species 2 from the "species1" fragment library.  If you had CO2 listed before N2 in the input file when you generated these fragment libraries and then flipped the order afterward without replacing the fragment libraries, then I suppose this could work despite being confusing, but I don't recommend it.
- Your `Rcutoff_Low` is 0.3 Å for GCMC but it's 1.0 Å for Widom insertions.  For most systems, a cutoff of 1.0 Å is fine and decreasing it to 0.3 Å would effectively only slow the simulation, but if this is not the case for this system, that could cause problems.  As far as I know, there's no good reason to decrease the `Rcutoff_Low` when going from Widom insertions to GCMC, in any case.
- **Your temperature for the GCMC simulations has two decimal points.  I am very confident that this breaks your simulation.**  Cassandra currently does not verify that the numbers you give it are actually valid string representations of a number.  There's a work-in-progress PR #125 to add an error message that triggers when Cassandra tries to convert a string to a double or integer but the string is not a valid string representation of a double or integer, but until it is included, the user is solely responsible for making sure that the numbers in their input files are valid string representations of the required numerical values.  "315.15." is not a valid number.

**Comment by emarinri** [comment]
Hello @camjjr!

The PR #125 that @rwsmith7531 mentioned has been merged in the master branch. Please let us know if this fixes your problem.

**Comment by camjjr** [comment]
Thank you @rwsmith7531 @emarinri 
The problem was the two points in the temperature. Now Cassandra is giving a consistent value

**Comment by rwsmith7531** [comment]
Thank you for the update @camjjr .  I am glad it's working for you.  I am now closing the issue.
