### ISSUE TITLE
Cloning repo is slow

### ISSUE THREAD

**Issue by mattwthompson** [MaginnGroup/Cassandra#34]
When cloning, at least without any special flags:

```
$ git clone https://github.com/MaginnGroup/Cassandra.git
```

we get the entire `git` history in the `.git` hidden directory, which happens to be quite large. This may be due to some binaries being tracked in the history, which can balloon the size quickly. Here is a snapshot of my clone:

![image](https://user-images.githubusercontent.com/7935382/76471040-a2d51b80-63bf-11ea-94c0-f318526dfb7d.png)

I will tag https://github.com/GOMC-WSU/GOMC/issues/154 as the source of my deja vu (strangely enough, the histories are nearly the same size) and @justinGilmer, who noted this in GOMC, and @YounesN, who is probably responsible for fixing it there.

**Comment by rsdefever** [comment]
Thanks for bringing this to our attention. I will look into it. First glance suggests it may be coming from some fragment library files that are distributed with Examples/.

**Comment by rsdefever** [comment]
@mattwthompson Thanks again for bringing this to our attention. We have cleaned up the repo history. Now down to `11 MB` in `.git` and `47 MB` total. As you probably know, this required re-writing the git history. You'll probably want to re-clone and force push to your remote. Or just delete and re-fork. 

Thanks again!
