### ISSUE TITLE
Checkpoint files with dashes result in error

### ISSUE THREAD

**Issue by rmatsum836** [MaginnGroup/Cassandra#87]
## Is your feature request related to a problem? Please describe.
I ran into an issue where I was trying to restart a simulation from a checkpoint file named `equil-rst.out.chk`.  I found the same issue addressed here: https://cassandra.nd.edu/index.php/forum/cassandra-software/300-problem-restarting-simulation.

## Describe the solution you'd like
I think it's okay to not allow dashes in the file names, but I think the default name for restart simulations (`equil-rst`) should be changed to something like `equil_rst` to fit this naming convention.  In addition, improve the documentation to make it clear that dashes are not allowed.

## Describe alternatives you've considered
Alternatively, the code could be refactored to allow dashes in the file names, but this may be a much more complicated solution.

## Additional context
- Cassandra 1.2.5

## Further information, files or links (optional)
Any additional information here, attach relevant text or image files and URLs to external sites, publications , etc

**Comment by rsdefever** [comment]
@rwsmith7531 I know you've looked into this. I think you concluded there is no good reason to prevent dashes in the file name. 

@emarinri @ryangmullen do either of you know the reason that Cassandra prevents `-` in the file name? Can either of you think of any reason that we shouldn't relax that restriction?

**Comment by rmatsum836** [comment]
Also need to add that I was using `mosdef_cassandra` which was the culprit of adding `-rst` to the end of the filename.

**Comment by rsdefever** [comment]
@rmatsum836 I'm going to close this issue. Can you open one in the `mosdef_cassandra` repo?
