### ISSUE TITLE
Limits to integer size - long solubility runs

### ISSUE THREAD

**Issue by bbefort** [MaginnGroup/Cassandra#97]
I have been running a simulation for ~2 billion steps without issue. When I restart to run for beyond 2 billion steps, the simulation says it is complete. This may be an issue with the size of numbers which the program can store.

Attached are the input files needed to check this problem. In R32_bmimpf6_fail.zip the input file results in the issue discussed above. In R32_bmimpf6_success.zip the input file is only set to run for a short amount of time and is successful at restarting.
[R32_bmimpf6_fail.zip](https://github.com/MaginnGroup/Cassandra/files/6183027/R32_bmimpf6_fail.zip)
[R32_bmimpf6_success.zip](https://github.com/MaginnGroup/Cassandra/files/6183028/R32_bmimpf6_success.zip)

**Comment by rsdefever** [comment]
Thanks for pulling together these examples @bbefort. I've already looked at the code, and it looks like we are using a 32 bit integer, so that would make sense. I'll assign this to myself and try to get a fix submitted in a couple of days.
